# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160823_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.TextField(max_length=100),
        ),
    ]
