# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.ImageField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
