# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160823_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.CharField(default='summer', max_length=100),
        ),
    ]
