# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_document_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='gallerythumbs/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tag',
        ),
        migrations.AddField(
            model_name='document',
            name='gallery',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Gallery'),
        ),
    ]
