# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20160824_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, default='00000', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='gallery',
            field=models.ForeignKey(default='0000000', editable=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.Gallery'),
        ),
    ]
